### PR TITLE
Add argument for run binary

### PR DESCRIPTION
**Pull request by bukton123**
Also added argument for running binary

Example: config
```toml
bin = "tmp/main"
args_bin = ["server"]
```

Output
```
tmp/main server
```

### CODE REVIEW

**Comment by hnlq715** [comment]
Any updates?

**Comment by marmiha** [comment]
Nice, I've pulled your repo and built it. It works, thanks!

**Comment by marmiha** [comment]
> Nice, I've pulled your repo and built it. It works, thanks!

Actually not, it tries to delete the wrong file, as the bin path is concated with args

**Comment by xiantang** [comment]
already supported. thanks

**Pull request closed without merging**
