### PR TITLE
feat: silent flag in .air.toml, suppressing all air prints

### PR DESCRIPTION
**Pull request by jesses-code-adventures**
useful if the app being watched has structured outputs that are being piped into subsequent program/s.

### CODE REVIEW

**Comment by silverwind** [comment]
Will errors still show with this flag enabled? If so, it should be fine imho.

**Comment by jesses-code-adventures** [comment]
this library generally uses log.Fatalf() for errors, whereas these changes only affect info and debug logs in runner/util.go and runner/logger.go which produce the lion's share of the logs. shouldn't be anything to worry about as far as errors being suppressed.

**Comment by cosmtrek** [comment]
@jesses-code-adventures Hi, thanks for adding the silent flag, could you rebase the master and rerun the checks?

**Comment by jesses-code-adventures** [comment]
@cosmtrek i have rebased the master but i don't believe i can trigger the checks on my end. please let me know if I'm wrong on this though, happy to add an explanation to the readme if contributors can run the checks.

**Pull request merged**
