### PR TITLE
Implement graceful shutdown on Mac

### PR DESCRIPTION
**Pull request by xiantang**
close https://github.com/air-verse/air/issues/534

### CODE REVIEW

**Comment by ccoVeille** [comment]
So it's about

- #534

Easier for everyone, and allow crossing issue and PR

**Comment by ccoVeille** [comment]
Title is not used for resolving and quoting issues and PR relationship.

Especially there were you used an URL and not an hash (and I'm unsure it would have worked anyway)

Description and comments are the perfect candidates when dealing with GitHub relationship

**Comment by xiantang** [comment]
> Title is not used for resolving and quoting issues and PR relationship.
> 
> Especially there were you used an URL and not an hash (and I'm unsure it would have worked anyway)
> 
> Description and comments are the perfect candidates when dealing with GitHub relationship

gotcha, thank you

**Comment by ccoVeille** [comment]
PR superseeded and replaced by #619

**Pull request closed without merging**
